### ISSUE TITLE
i am trying to open a half gig of the moon tif on android 11.

### ISSUE THREAD

**Issue by jekv2** [max-kammerer/orion-viewer#109]
so i am trying to open a half gig of the moon tif on android 11.

https://skyandtelescope.org/astronomy-news/a-half-gigabyte-view-ofthemoon/

http://lroc.sese.asu.edu/data/pr/tiff/wac_nearside.tif

orion fails to open it.

**Comment by max-kammerer** [comment]
@jekv2 Could you please provided additional details and/or crash log? 
Crash log could be taken from devices for example via android debug bridge (adb, part of Android SDK) or ADB AppControl (thirdparty app).

**Comment by jekv2** [comment]
> @jekv2 Could you please provided additional details and/or crash log? Crash log could be taken from devices for example via android debug bridge (adb, part of Android SDK) or ADB AppControl (thirdparty app).

in fact it works, just takes time to ooen it which is understandable as it is 500MB image.

i apologize.
![Screenshot_20241206-141033](https://github.com/user-attachments/assets/f291d734-020a-4438-ab46-7f2003622280)
![Screenshot_20241206-141023](https://github.com/user-attachments/assets/c4686b6f-83ae-4a7e-8d60-da0a534eb789)

**Comment by max-kammerer** [comment]
@jekv2 Cool! I wonder how long it takes to open a file?

**Comment by jekv2** [comment]
> @jekv2 Cool! I wonder how long it takes to open file?

on the xperia 5 iii with the image on the new 2TB sdxc card by sandisk. 16seconds. 👍
