### ISSUE TITLE
Opening djvu stucks on android 7 devices 

### ISSUE THREAD

**Issue by izjumovfs** [max-kammerer/orion-viewer#13]
Hello! I can't open current files by orion-viewer. I tried to open them on three devices: Xiaomi Redmi Note 3 (android 7.1.1), Geotel A1 A1 (android 7.0) and Vernee Mars (android 7.0). During opening file, the page size is recognized, than when the page is trying to be shown everything stucks. No log, no errors. The latest log message is "Page number " and that's all. Other android devices (android 4, 5, 6) open these files without any troubles, just long preloader (10sec max). I would be very glad, if You answer me as soon as possible. Thank You!
[journal.zip](https://github.com/max-kammerer/orion-viewer/files/1014446/journal.zip)

**Comment by max-kammerer** [comment]
Which version did you tried?

**Comment by max-kammerer** [comment]
Try this one (rename to apk):
[djvu-arm.zip](https://github.com/max-kammerer/orion-viewer/files/1017117/djvu-arm.zip)

**Comment by izjumovfs** [comment]
Thanks for reply. I'll try this apk an will write about my progress

**Comment by max-kammerer** [comment]
@izjumovfs not they are not checked in, need to perform some cleaning

**Comment by izjumovfs** [comment]
I will be very pleased if you will notify me when the source code will be updated. Thanks again)

**Comment by max-kammerer** [comment]
@izjumovfs pushed
