### ISSUE TITLE
Can't use auto crop

### ISSUE THREAD

**Issue by seacatwu** [max-kammerer/orion-viewer#14]
When I use auto crop , the document become strip, which I want suit the width without blank.

**Comment by max-kammerer** [comment]
@seacatwu Which Orion version  do you use? Could you attach sample book?

**Comment by seacatwu** [comment]
orion-viewer-0.74.2-arm7
orion-viewer-0.74.1-arm7
I have used these version, and found that bug, and it happens all the pdf book.....

**Comment by seacatwu** [comment]
I found it works good in my phone, but it not works on my eink device. I'll try this again tomorrow when I get in my office.

**Comment by seacatwu** [comment]
My eink device's CPU is Freescale i.MX6. 
Which version should I use?
@max-kammerer

**Comment by seacatwu** [comment]
I tried some pdf in my eink device, and the bug is still....
I can't upload pdf to the github. Can you give me you email, and I'll send the pdf to you.

**Comment by max-kammerer** [comment]
@seacatwu arm7 build should work, could you send me log file during auto crop operation (you could take it via aLogCat or by another program), seem pdf is not necessary.

**Comment by max-kammerer** [comment]
Problem was in wrong apk file installed on device. Should be arm5.
@seacatwu thanks for investigation!
