### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by dimqua** [max-kammerer/orion-viewer#15]
Please consider to add the app to F-Droid repository. 

Thanks

**Comment by IzzySoft** [comment]
@dimqua looks like this projecgt is no longer maintained (no commit for 1.5 years, and your issue still not responded to) 😢

**Comment by max-kammerer** [comment]
Sorry for unanswered issue.

There was several propasal in f-droid forum a long time ago, but without any  progress.
Yes project a bit frozen

**Comment by max-kammerer** [comment]
https://f-droid.org/forums/post/9471/index.html

**Comment by IzzySoft** [comment]
Oh, that was ages ago (5+ years). OK, so if you "thaw" this project, please let us know (just comment here) so we can check again.

Thanks!

**Comment by max-kammerer** [comment]
@IzzySoft there are some experiments in non-master branch, but if you want to add project to f-droid 'master' branch is stil suitable for that.

**Comment by IzzySoft** [comment]
Thanks, @max-kammerer! But with the master branch not updated for 1.5 years, wouldn't it be better to add it when you finished your experiments (or "merged a stable variant" to master)? Any raw ETA when that might be?

PS: Glad to see this project is still alive and kicking! :+1:

**Comment by max-kammerer** [comment]
@IzzySoft There is no any ETA for experiment branch

**Comment by IzzySoft** [comment]
I see, thanks. Please ping me (comment here) when things change 😉

**Comment by max-kammerer** [comment]
@IzzySoft you could try to publish fresh 0.80.6 version

**Comment by IzzySoft** [comment]
Thanks @max-kammerer – my updater picked it, will be live [in my repo](https://apt.izzysoft.de/fdroid/index/apk/universe.constellation.orion.viewer) with the next sync in 11 hours. If you wish to bring it into the "big repo" at f-droid.org, I can help you open an RFP (Request For Packaging) there, just let me know then. For that, it would be great if you could establish [Fastlane file structure](https://gitlab.com/snippets/1895688) here in your repo, so you can maintain summary/description yourself (without additional MRs each time you need to change them) as well as to provide screenshots and maybe even per-release changelogs. Of course it's absolutely fine if you just want your app to stay with my repo; in that case, at least the per-release changelogs would be picked by my updater :wink:

**Comment by TPS** [comment]
@max-kammerer For the record, _posting_ an F-Droid RFP can take as little as 5 minutes.  The prereqs that @IzzySoft mentioned may take a bit longer.

**Comment by TPS** [comment]
v0.80.6 is now live via @IzzySoft's repo.

@max-kammerer Any thoughts re: adding the info req'd for F-Droid's?

**Comment by max-kammerer** [comment]
@TPS @IzzySoft Could you explain a bit how works F-Droid infrastructure and what differences between main repo and @IzzySoft ones? 
Am I correct that without FLS only current version would be published on F-Droid? 
With FLS it would be done automatically on each release?
In both case I need RFP?

@IzzySoft There is only one apk in your repo, but actually Orion supports 4 architecture and there are 4 apks (each with same size as one published in your repo)

**Comment by IzzySoft** [comment]
> Could you explain a bit how works F-Droid infrastructure and what differences between main repo and @IzzySoft ones?

May I recommend my article series for that? [F-Droid: The privacy-friendly alternative to Google Play Store](https://android.izzysoft.de/articles/named/fdroid-intro-1) There are many repos, each can have its own set of rules (and usually has its own kind of infrastructure). F-Droid's is strictly FOSS, others might be more lenient – and usually are focused on specific topics.

> Am I correct that without FLS only current version would be published on F-Droid?

What is FLS?

> There is only one apk in your repo, but actually Orion supports 4 architecture and there are 4 apks (each with same size as one published in your repo)

Yes, I know. But my repo runs on "personal space", so it's limited to 30M per app. Further it supports only 1 APK per app and version. That's why I usually pick the `armeabi` one of multi-arch projects, as ARM is the most wide-spread architecture on Android, and with `armeabi` close to 90% are covered.

**Comment by max-kammerer** [comment]
> What is FLS?

Fastlane file structure

**Comment by max-kammerer** [comment]
There some response from user about last  version, I hope there would be new version in a few days and we can open F-Droid RFP

**Comment by IzzySoft** [comment]
Just cross-link the issues then (from the RFP here, and from here to the RFP) for easier following. I'll keep an eye on it and do my best to get it through then.

**Comment by max-kammerer** [comment]
RFP: https://gitlab.com/fdroid/rfp/-/issues/1343

**Comment by IzzySoft** [comment]
Cool! Waiting for the bot to check then. Meanwhile: Could you take a look at my [Fastlane Cheat-Sheet](https://gitlab.com/snippets/1895688) and see if you can integrate those structures (at least the basic ones: summary, description and screenshots for `en-US`) with your repo here?

**Comment by max-kammerer** [comment]
Application is distributed through 4 apks (for arm7, arm64, x86 or x86_64 architecture). And each apk have it's own version code (x, x+1, x+2, x+3). Which version should I use for changelog?

**Comment by IzzySoft** [comment]
Good question, I don't know. For me arm7, but for F-Droid? Maybe use all (one with content, the other symlinks) – and ask the packager when he's on it?

**Comment by max-kammerer** [comment]
I've added simple fastlane support, but without changelog: https://github.com/max-kammerer/orion-viewer/commit/bdd536f9efe4fc314477de387733ec2fc27d6a5e

**Comment by IzzySoft** [comment]
That's fine for F-Droid, I'd say merge it and tag it (though some of the screenshots look a bit, um, old – even pre-Gingerbread :rofl:). per-release changelogs can be added anytime later. The most important things to have there are the short- and full description, so you don't require another MR to bring it in. Thanks!

**Comment by max-kammerer** [comment]
@IzzySoft  I've updated old graphics to new one in new commit and merge it into master. I've also added changelog for the lowerest version in current release (182.txt). Commit is tagged with '0.80.7_fdroid'

**Comment by IzzySoft** [comment]
Thanks! F-Droid currently only picks (and shows) release notes for the most recent release anyway, so that totally suffices. As for tag names: do you plan to keep the `_fdroid` suffix? Because once we've setup the metadata and merged it, you'd be fixed to what we setup and other tags would be ignored (changing that would require another MR then). The most common tag pattern is `v<versionName>` – second most-used without the leading `v` (as your other tags are).

**Comment by max-kammerer** [comment]
I would prefer to have same tags (x.xx.x). 
Would `0.80.7.1` ok for fdroid with this release?

**Comment by IzzySoft** [comment]
That's fine. And yes – as long as it's matched by `versionName '0.80.7.1` :smiley:

**Comment by max-kammerer** [comment]
tagged

**Comment by IzzySoft** [comment]
Thanks! Updated your RFP and marked it for our packagers. :crossed_fingers:

**Comment by IzzySoft** [comment]
@max-kammerer please remember to add new changelogs to fastlane when releasing new versions. Currently, all >182 are missing (last release is versionCode 190, but no `190.txt` there). Thanks!

**Comment by max-kammerer** [comment]
I've added minimum ones for 0.81.1/2

**Comment by IzzySoft** [comment]
Thanks! That looks fine. I've just updated Metadata in the RFP again, including  the use of `version.properties` for version check.

**Comment by max-kammerer** [comment]
Orion Viewer is available on f-droid now: https://www.f-droid.org/en/packages/universe.constellation.orion.viewer/

**Comment by IzzySoft** [comment]
Congrats @max-kammerer! So usually, in a few days I'd remove the app from my repo, unless explicitly requested not to (see [here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ) for some background). What is your opinion on that?

Oh, I just looked at the metadata: `AppAdded: 2016-06-22`. Wow, close to the 5th anniversary – Orion Viewer must have been one of the first apps in my repo (which started around 2016-03 IIRC)!

**Comment by max-kammerer** [comment]
@IzzySoft I'm OK with removing. 
Thank you for help with publishing Orion on F-Droid)

**Comment by IzzySoft** [comment]
1. thanks, marked
2. gladly done :smiley:
3. as we've almost made it: happy 5th anniversary nevertheless – we've been so close to it!
4. you might consider adding the F-Droid badge to the Readme, next to Google's. Alphabetic order preferred :rofl:

**Comment by max-kammerer** [comment]
Hello @IzzySoft! What is current way to update Orion on f-droid?

**Comment by IzzySoft** [comment]
Fixing issue https://gitlab.com/fdroid/fdroiddata/-/issues/2989 – auto-updates are currently disabled for the reason described there. Sorry, I cannot help with that.

**Comment by max-kammerer** [comment]
>can you link to the binary policy of jetbrains? How are those binaries built? Etc?

@goodwinnk Could you please help to answer question raised in (f-droid discussion)[https://gitlab.com/fdroid/fdroiddata/-/issues/2989#note_1616625908]? These questions are about built policy for `kotlin-native-prebuilt` artifacts.
(Feel free to answer here, I will point to your answer in dedicated thread, or maybe you can point to somebody else that can help with answering these questions)
