### ISSUE TITLE
Opening djvu stucks on android 7 devices

### ISSUE THREAD

**Issue by izjumovfs** [max-kammerer/orion-viewer#17]
Hi. I have already described this issue in this [ticket](https://github.com/max-kammerer/orion-viewer/issues/13). And you have succesfully fixed it. But after a couple of commits - i am now again not able to open the journals (that were attached to the closed ticket) at my Android 7.0 devices. Please, could you take a look at the code and help to solve the issue? Thanks

**Comment by max-kammerer** [comment]
What version do you have installed?

**Comment by izjumovfs** [comment]
I have cloned and compiled the latest version from Github. Latest commit 10eb69c  on Jul 8, 2017

**Comment by max-kammerer** [comment]
Do you open djvu files? DjvuLibre was updated in 0.74.0 0 so reason could be in it. Could you check 0.73.x? Do you install arm5 version?

**Comment by max-kammerer** [comment]
And please send me log file for file open with last version

**Comment by max-kammerer** [comment]
Could you also try to rebuild native sources with fresh ndk and try to work with this build?

**Comment by max-kammerer** [comment]
Yes, you could use thirdparty_build.gradle, just update ndk.dir path to latest one in prjojectRoot/local.properties

**Comment by max-kammerer** [comment]
@izjumovfs there is separate branch with updated djvlibre and build toolchain (you will need ndk 16b) - mig4
So if issue is still actual you can check it aganst new sources

**Comment by max-kammerer** [comment]
@izjumovfs Could you reproduce issue with 0.80.6 version?

**Comment by max-kammerer** [comment]
@izjumovfs I'm closing this issue as obsolete, feel free to reopen it if you still has this problem
