### ISSUE TITLE
Is it possible to speed up page rendering?

### ISSUE THREAD

**Issue by izjumovfs** [max-kammerer/orion-viewer#18]
Hi. I am wondering - is it possible to make page rendering more fast? Some documents have very big page resolutions and rendering becomes a real head-ache for many Android devices. Is it possible to make render process faster and maybe render scaled bitmaps - not the real size page. 
And the other question - are we able to cancel render tasks. For example i have a RecyclerView with 5 pages. And i am going to render all them in a separate threads. I can cancel my task, but the job on the native side will be still working, till all the 5 requests reach their ends. And to load and display - 5 new images - i need to wait till prev 5 will be finished.Can we stop the on the native sides - and start load new pictures?
Thanks

**Comment by max-kammerer** [comment]
"Is it possible to make render process faster and maybe render scaled bitmaps - not the real size page."
Page are always rendered in scaled bitmap.
"Can we stop the on the native sides - and start load new pictures?"
It's best to investigate on native libraries side.

**Comment by izjumovfs** [comment]
So, at the moment we cannot speed up page rendering. Some large pages are loading very long
You can download these journals to see [journal.zip](https://github.com/max-kammerer/orion-viewer/files/1014446/journal.zip)

**Comment by max-kammerer** [comment]
Fresh 0.93.2 version has a bunch of performance optimization, hope it will solve issues with large page/document loading
