### ISSUE TITLE
Invisible menu items on Boyue Likebook Mars T80D

### ISSUE THREAD

**Issue by bezigon** [max-kammerer/orion-viewer#20]
Hello, @max-kammerer!
I have issue with invisible menu items on my device.

Android: 6.0.1
Hardware: rk30board
Platform: rk3368

![IMG_0004](https://user-images.githubusercontent.com/771853/63210342-cd931600-c0f5-11e9-9e4e-9f813d47de08.JPG)

**Comment by max-kammerer** [comment]
@bezigon Thanks for bug, as workaround you can try to change application theme in application settings (and restart application)

**Comment by max-kammerer** [comment]
@bezigon Please try last 0.80.6 release. 
If it's no fix problem than most likely it's problem with theme avaliable on device

**Comment by bezigon** [comment]
@max-kammerer not fixed, but thanks anyway!

**Comment by max-kammerer** [comment]
@bezigon in which dialog it's appeared? It's only one or several ones?

**Comment by max-kammerer** [comment]
@bezigon  Thank you for the report and sorry for the long delay. The upcoming 0.92.3 release will ship reworked preference and it should solve this problem. You can try the last Beta to check the fix on https://sourceforge.net/projects/orion-viewer/files/
