### ISSUE TITLE
Incorrect book is opened via "recent books" dialog

### ISSUE THREAD

**Issue by bahusoid** [max-kammerer/orion-viewer#21]
To reproduce the issue:
1) Open multiple books  so "recent books" dialog is not  empty and contains at least 2 books;
2) Open "recent books" dialog and open second book from list (let it be Book2)
3) Correct book (Book2) is opened
4) Now go back to recent books dialog and open first book from list (let it be Book1)
5) Book2 is opened again instead of Book1

Seems order of books is changed so the last opened one become on the top but list of names remains the same

**Comment by max-kammerer** [comment]
Thank you for reporting issue! Fixed!

**Comment by bahusoid** [comment]
Thanks for quick fix!
