### ISSUE TITLE
Page jumps to the previous position for a moment when I scroll it via swiping

### ISSUE THREAD

**Issue by SerVB** [max-kammerer/orion-viewer#26]
For some years, I experience this painful glitch.

When I want to move a page, I drag my finger, and when I end dragging and put my finger up, for a moment I see that the page jumps to the position where it was before this dragging. And almost immediately it goes to the right position, where I wanted to scroll it.

This is not a convenient behavior for scrolling. So I try not to use it now, but when it's fixed, I will!

AFAIR I have experienced this behavior on all of my devices. They have IPS and AMOLED screens. Maybe this issue exists since this scrolling is implemented.

**Comment by max-kammerer** [comment]
@SerVB thank you for the issue! Fix will be shipped in upcoming 0.90.0 release
