### ISSUE TITLE
In Dark Mode, menus are blank on e-ink devices

### ISSUE THREAD

**Issue by MarjaE2** [max-kammerer/orion-viewer#27]
I somehow got stuck in Dark Mode.

The page traversal menu can be important.

I get a single unreadable grey box in the upper left corner and have to pick without seeing anything.

Maybe it's a color mode issue...?

I get nothing and have to pick without seeing anything.

Maybe contrast?

I get nothing.

**Comment by MarjaE2** [comment]
By Dark Mode I mean the Application Theme.

**Comment by max-kammerer** [comment]
Which device do you have?

**Comment by MarjaE2** [comment]
Likebook Mars.

**Comment by max-kammerer** [comment]
Could you also attach image?

**Comment by MarjaE2** [comment]
![Screenshot_20201216-071721](https://user-images.githubusercontent.com/12875862/102287124-be012880-3f07-11eb-8d3a-039a81b8ba72.png)
![Screenshot_20201216-071819](https://user-images.githubusercontent.com/12875862/102287130-c0638280-3f07-11eb-89d3-7d0cb92378ad.png)

Those are in default rather than dark mode, but show the problem.

**Comment by max-kammerer** [comment]
@MarjaE2  Thank you for the report and sorry for the long delay. The upcoming 0.92.3 release will ship reworked preference and it should solve this problem. You can try the last Beta to check the fix on https://sourceforge.net/projects/orion-viewer/files/
