### ISSUE TITLE
Potentially vulnerable PDF library used

### ISSUE THREAD

**Issue by SkewedZeppelin** [max-kammerer/orion-viewer#40]
I am going though apps that use old native libraries on F-Droid: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11496/

Your app uses MuPDF 1.16.1 from 2019-08-02, which seems to have ~5 known security issues.
https://github.com/max-kammerer/orion-viewer/commits/0.81.2_fdroid/nativeLibs/mupdfModule

Newer versions are available: https://mupdf.com/releases/history.html

**Comment by max-kammerer** [comment]
@SkewedZeppelin Thank you for the report!

**Comment by max-kammerer** [comment]
@SkewedZeppelin Thank you for the report! Orion 0.82.1 is shipped with mupdf 1.23.3
