### ISSUE TITLE
Can't exit out of any options menus

### ISSUE THREAD

**Issue by philgoetz** [max-kammerer/orion-viewer#42]
I'm using a Nook Glowlight 3+ (2018).
After I go into CURRENT BOOK OPTIONS, there's no way to get out other than to reboot my Nook.
There are no back-arrows or any other indications anywhere on the screen that there's any way to leave that menu, and I've tried tapping all over the screen, and pressing all the Nook buttons.

Similarly with DEFAULT BOOK SETTINGS. I can see faint outlines of the top halves of the icons in the upper-right corner, but they're always hidden behind the bar for the top menu item, and also they are just outlines, with no pixels in the interior lit up; and they do nothing if I try to touch them.

Also, after opening a PDF, there's no way to close it and open another PDF.
I suspect all these open PDFs are left running in the background, but have no way to check what processes are running.

It looks nice otherwise!

My guess is that you're relying on the Android phone's back-arrow button. E-readers don't have those.

**Comment by max-kammerer** [comment]
@philgoetz Thank you for the report and sorry for the long delay. The upcoming 0.92.3 release will ship reworked preference and I hope it will solve your problems with them. You can try the last Beta to check the fixes on https://sourceforge.net/projects/orion-viewer/files/

>Also, after opening a PDF, there's no way to close it and open another PDF.

This point is no clear for me, main menu in default UI should have 'Exit' and `Open new book`  menu action
