### ISSUE TITLE
Orion viewer gone. New app name is File Manager

### ISSUE THREAD

**Issue by symbuzzer** [max-kammerer/orion-viewer#47]
![Screenshot_20240426-093835_Trebuchet](https://github.com/max-kammerer/orion-viewer/assets/9841184/6940d6c8-6e4d-498e-830b-1d4c9722f105)

**Comment by max-kammerer** [comment]
@symbuzzer Thank you! Will fix soon!

**Comment by max-kammerer** [comment]
@symbuzzer fixed! Thank you!
