### ISSUE TITLE
Changing indivual book, and or default book Color Mode in 92.1 and 92.2 does not work at all.

### ISSUE THREAD

**Issue by Smutley** [max-kammerer/orion-viewer#49]
Changing indivual book, and or default book Color Mode in 92.1 and 92.2 does not work at all.

While it has always been awkward, and often niggley, changing Color Mode for individual books, and or as a default, at least worked. The last two releases it does not work at all, and the "default" color is always shown regardless of setting.

**Comment by max-kammerer** [comment]
@Smutley thank you for the report. I will look into it.

Could you please add additional detail about this part "While it has always been awkward, and often niggley", what was wrong in case when this option worked

**Comment by max-kammerer** [comment]
@Smutley I've made several fixes. You can try the latest beta version to test the corrected behavior: https://sourceforge.net/projects/orion-viewer/files/

**Comment by Smutley** [comment]
Your changes in 92.3 make the color mode work more or less as in earlier than 92.2 releases.

However, setting default color mode only works if a document is open when a color change is made. Nor will it reliably work unless one changes to yet another color mode, and then changes to the desired color mode. In other words it does not work as expected.

**Comment by max-kammerer** [comment]
@Smutley The logic behind option is next: default option works for current opened book and for all new books that would be open in future. There is also "color mode" option  for current book in "[Current] Book option" (it's separate menu item)

>Nor will it reliably work unless one changes to yet another color mode, and then changes to the desired color mode

I don't understand this part. Maybe you can add additional details, how to reproduce the problem and what are initial setting to start with

**Comment by max-kammerer** [comment]
@Smutley I'm closing this issue as original problem was fixed. If you have any ideas about option logic improvements please report additional issue
