### ISSUE TITLE
[Feature Req] add webp image support

### ISSUE THREAD

**Issue by Ero-gamer** [max-kammerer/orion-viewer#51]
I'm surprised webp image format is still unsupported even though it was added to Android way back then on Android 4.2.1.

**Comment by max-kammerer** [comment]
@Ero-gamer Thank you for the request. Could you please add some clarification for it (why do you want to see it in Orion; how it supported in other apps and what problem with such support; any other thoughts). My aim here is quite simple - understand priority for other image format support or focus more on book ones.  Supporting small number of image formats in recent versions of Orion is more like experiment.

**Comment by Ero-gamer** [comment]
> @Ero-gamer Thank you for the request. Could you please add some clarification for it (why do you want to see it in Orion; how it supported in other apps and what problem with such support; any other thoughts). My aim here is quite simple - understand priority for other image format support or focus more on book ones. Supporting small number of image formats in recent versions of Orion is more like experiment (that is free of cost cause of delegation to Mupdf library).

Your app is lightweight yet it has many features and a good reader. I have alot of Manga/webtoons books in cbz archive stored as webp, I mainly read them on TachiyomiSY app but it use more RAM on my low-end phone so I tried looking for alternative lite app that do the same job but use less RAM. There are many image decoder libraries that support webp like coroutines, Glide and [Coil](https://github.com/coil-kt/coil) (which has the best image rendering applied by default) so maybe you can try to implement [Coil](https://github.com/coil-kt/coil) library as image decoder? I think it will be a great addition since it's optimized to run fast and use less resources among other things.

**Comment by max-kammerer** [comment]
> I have alot of Manga/webtoons books in cbz archive stored as webp

If I understand you properly the request is to support zip files (cbz) with webp images inside

**Comment by Ero-gamer** [comment]
> > I have alot of Manga/webtoons books in cbz archive stored as webp
> 
> If I understand you properly the request is to support zip files (cbz) with webp images inside

Precisely.
