### ISSUE TITLE
Text entered into search dialog does now show in certain color modes.

### ISSUE THREAD

**Issue by Smutley** [max-kammerer/orion-viewer#52]
Text entered into search dialog does now show up in certain color modes. 

If a color mode is set to inverted colors, or to dark blue and white, text entered into the search dialog does not show as you type. This is because the text color is the same as, or very similar to, the the background of the of search dialog.

Expected behavior: You should be able to see what you type in the search dialog.

**Comment by max-kammerer** [comment]
@Smutley Thank you for the report! Problem is fixed in 0.94.0 version
