### ISSUE TITLE
translation error

### ISSUE THREAD

**Issue by alotbsol555** [max-kammerer/orion-viewer#90]
the string in line 6 should be in english, like the rest of the file:

https://github.com/max-kammerer/orion-viewer/blob/master/orion-viewer%2Fsrc%2Fmain%2Fres%2Fvalues%2Ffileopen.xml#L6

I don't want to just change it, because it's the basis for all translations. Suggestion:

"Can't access file directly, please choose an option below:"

**Comment by max-kammerer** [comment]
@alotbsol555 Thank you! Nice catch!
